// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Default permissions for a domain (Office or Room).
 * These define what actions are allowed by default for users in that domain.
 * Read operations default to `true`, write/admin operations default to `false`.
 */
export type DomainPermissions = { 
/**
 * Whether users can view content in this domain
 */
view_content: boolean, 
/**
 * Whether users can read messages in group chat
 */
read_messages: boolean, 
/**
 * Whether users can download files
 */
download_files: boolean, 
/**
 * Whether users can edit content (documents, etc.)
 */
edit_content: boolean, 
/**
 * Whether users can edit MDX content
 */
edit_mdx: boolean, 
/**
 * Whether users can send messages in group chat
 */
send_messages: boolean, 
/**
 * Whether users can upload files
 */
upload_files: boolean, 
/**
 * Whether users can create rooms in this office
 */
create_room: boolean, 
/**
 * Whether users can delete rooms
 */
delete_room: boolean, 
/**
 * Whether users can update room settings
 */
update_room: boolean, 
/**
 * Whether users can add rooms
 */
add_room: boolean, 
/**
 * Whether users can edit room configuration
 */
edit_room_config: boolean, 
/**
 * Whether users can update room settings
 */
update_room_settings: boolean, 
/**
 * Whether users can manage room members
 */
manage_room_members: boolean, 
/**
 * Whether users can create offices
 */
create_office: boolean, 
/**
 * Whether users can delete offices
 */
delete_office: boolean, 
/**
 * Whether users can update offices
 */
update_office: boolean, 
/**
 * Whether users can add offices
 */
add_office: boolean, 
/**
 * Whether users can edit office configuration
 */
edit_office_config: boolean, 
/**
 * Whether users can update office settings
 */
update_office_settings: boolean, 
/**
 * Whether users can manage office members
 */
manage_office_members: boolean, 
/**
 * Whether users can create workspaces
 */
create_workspace: boolean, 
/**
 * Whether users can update workspaces
 */
update_workspace: boolean, 
/**
 * Whether users can delete workspaces
 */
delete_workspace: boolean, 
/**
 * Whether users can edit workspace configuration
 */
edit_workspace_config: boolean, 
/**
 * Whether users can add other users to this domain
 */
add_users: boolean, 
/**
 * Whether users can remove users from this domain
 */
remove_users: boolean, 
/**
 * Whether users can ban users from this domain
 */
ban_user: boolean, 
/**
 * Whether users can manage domains
 */
manage_domains: boolean, 
/**
 * Whether users can configure system settings
 */
configure_system: boolean, 
/**
 * Whether users can edit tree structure (add/remove/rearrange nodes)
 */
edit_tree_structure: boolean, 
/**
 * Whether users can manage custom node types
 */
manage_node_types: boolean, };
