// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Default permissions for a domain node.
 * These define what actions are allowed by default for users in that node.
 * Read operations default to `true`, write/admin operations default to `false`.
 */
export type DomainPermissions = { 
/**
 * Whether users can view content in this domain
 */
view_content: boolean, 
/**
 * Whether users can read messages in group chat
 */
read_messages: boolean, 
/**
 * Whether users can download files
 */
download_files: boolean, 
/**
 * Whether users can edit content (documents, etc.)
 */
edit_content: boolean, 
/**
 * Whether users can edit MDX content
 */
edit_mdx: boolean, 
/**
 * Whether users can send messages in group chat
 */
send_messages: boolean, 
/**
 * Whether users can upload files
 */
upload_files: boolean, 
/**
 * Whether users can create child nodes
 */
create_node: boolean, 
/**
 * Whether users can delete child nodes
 */
delete_node: boolean, 
/**
 * Whether users can update child nodes
 */
update_node: boolean, 
/**
 * Whether users can add child nodes
 */
add_node: boolean, 
/**
 * Whether users can edit node configuration
 */
edit_node_config: boolean, 
/**
 * Whether users can update node settings
 */
update_node_settings: boolean, 
/**
 * Whether users can manage node members
 */
manage_node_members: boolean, 
/**
 * Whether users can create workspaces
 */
create_workspace: boolean, 
/**
 * Whether users can update workspaces
 */
update_workspace: boolean, 
/**
 * Whether users can delete workspaces
 */
delete_workspace: boolean, 
/**
 * Whether users can edit workspace configuration
 */
edit_workspace_config: boolean, 
/**
 * Whether users can add other users to this domain
 */
add_users: boolean, 
/**
 * Whether users can remove users from this domain
 */
remove_users: boolean, 
/**
 * Whether users can ban users from this domain
 */
ban_user: boolean, 
/**
 * Whether users can manage domains
 */
manage_domains: boolean, 
/**
 * Whether users can configure system settings
 */
configure_system: boolean, 
/**
 * Whether users can edit tree structure (add/remove/rearrange nodes)
 */
edit_tree_structure: boolean, 
/**
 * Whether users can manage custom node types
 */
manage_node_types: boolean, 
/**
 * Whether users can edit the workspace theme shown to every member.
 *
 * `serde(default)` because this field was added after records were already
 * being persisted. `DomainPermissions` is embedded in `DomainNode`, which
 * the backend reads with `serde_json::from_slice`, so a stored node written
 * before this existed has no `themes` key — and without a default the whole
 * read fails with `missing field themes`, taking the node map with it. An
 * upgrade would look like data loss rather than a schema change.
 *
 * It defaults to false, which is also the right direction for a
 * permission: an old record grants nothing it did not previously grant.
 */
themes: boolean, };
