// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Office } from "./Office";
import type { Room } from "./Room";
import type { Workspace } from "./Workspace";

export type Domain = { "Workspace": { workspace: Workspace, } } | { "Office": { office: Office, } } | { "Room": { room: Room, } };
