// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainPermissions } from "./DomainPermissions";
import type { NodeEntityType } from "./NodeEntityType";

/**
 * A unified node in the workspace hierarchy tree.
 * Replaces the separate Workspace/Office/Room structs with a single generalized type.
 */
export type DomainNode = { 
/**
 * Unique identifier for this node
 */
id: string, 
/**
 * Parent node ID. None = this is the workspace root
 */
parent_id: string | null, 
/**
 * Type of this node (Workspace or Child("Office"), Child("Room"), etc.)
 */
entity_type: NodeEntityType, 
/**
 * Depth in the tree (0=workspace root, 1=office-level, 2=room-level, etc.)
 */
depth: number, name: string, description: string, owner_id: string, members: Array<string>, 
/**
 * IDs of child nodes
 */
children: Array<string>, mdx_content: string, 
/**
 * SHA-256 of `mdx_content`, hex-encoded, computed by the SERVER on every
 * write.
 *
 * Rendering a document means executing it: the client compiles the MDX and
 * runs the result, so the bytes that reach the renderer must be the bytes
 * the server stored. The client re-hashes before it executes and refuses
 * on a mismatch.
 *
 * What this catches is tampering BETWEEN the server and the renderer — a
 * corrupted IndexedDB cache, a store-layer bug, another tab writing over
 * the content. It is not a defence against an attacker who already has
 * script execution in the page, who could patch the check itself; and it
 * says nothing about whether the document was hostile when it was written.
 *
 * `Option` because documents stored before this existed have no hash, and
 * a client must be able to tell "not hashed" from "hash does not match".
 */
mdx_content_hash: string | null, 
/**
 * Rules displayed to users
 */
rules: string | null, 
/**
 * Whether group chat is enabled for this node
 */
chat_enabled: boolean, 
/**
 * UUID for the group chat channel (assigned when chat_enabled is true)
 */
chat_channel_id: string | null, 
/**
 * Default permissions for users in this node
 */
default_permissions: DomainPermissions, 
/**
 * Flexible metadata for frontend use
 */
metadata: Array<number>, 
/**
 * If set, only these child types are allowed under this node
 */
allowed_child_types: Array<string> | null, 
/**
 * Whether this is the default node at its level (navigated to on login)
 */
is_default: boolean, created_at: bigint, updated_at: bigint, };
