// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of group message
 */
export type GroupMessageType = "Text" | "Markdown" | "System";
