// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListType = "MembersInWorkspace" | { "MembersInOffice": { office_id: string, } } | { "MembersInRoom": { room_id: string, } };
