// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataValue } from "./MetadataValue";

/**
 * Metadata field for storing flexible data used by the frontend
 */
export type MetadataField = { key: string, value: MetadataValue, };
