// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rule defining what child types are allowed under a parent type
 */
export type NestingRule = { 
/**
 * Parent node type (use "Workspace" for root, or child type names)
 */
parent_type: string, 
/**
 * Allowed child type names under this parent
 */
allowed_child_types: Array<string>, };
