// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Office = { id: string, owner_id: string, workspace_id: string, name: string, description: string, members: Array<string>, rooms: Array<string>, mdx_content: string, 
/**
 * Rules for this office (displayed to users)
 */
rules: string | null, 
/**
 * Whether group chat is enabled for this office
 */
chat_enabled: boolean, 
/**
 * UUID for the group chat channel (assigned when chat_enabled is true)
 */
chat_channel_id: string | null, metadata: Array<number>, };
