// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Office = { id: string, owner_id: string, workspace_id: string, name: string, description: string, members: Array<string>, rooms: Array<string>, mdx_content: string, metadata: Array<number>, };
