// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Permission = "All" | "CreateNode" | "DeleteNode" | "UpdateNode" | "CreateWorkspace" | "UpdateWorkspace" | "DeleteWorkspace" | "EditContent" | "AddUsers" | "RemoveUsers" | "EditMdx" | "EditNodeConfig" | "AddNode" | "UpdateNodeSettings" | "ViewContent" | "ManageNodeMembers" | "SendMessages" | "ReadMessages" | "UploadFiles" | "DownloadFiles" | "ManageDomains" | "ConfigureSystem" | "EditWorkspaceConfig" | "BanUser" | "EditTreeStructure" | "ManageNodeTypes";
