// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataField } from "./MetadataField";

export type Room = { id: string, owner_id: string, office_id: string, name: string, description: string, members: Array<string>, mdx_content: string, metadata: Array<MetadataField>, };
