// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataField } from "./MetadataField";

export type Room = { id: string, owner_id: string, office_id: string, name: string, description: string, members: Array<string>, mdx_content: string, 
/**
 * Rules for this room (displayed to users)
 */
rules: string | null, 
/**
 * Whether group chat is enabled for this room
 */
chat_enabled: boolean, 
/**
 * UUID for the group chat channel (assigned when chat_enabled is true)
 */
chat_channel_id: string | null, metadata: Array<MetadataField>, };
