// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The workspace's sign-in settings, as `GetSignInSettings` reads them and
 * `UpdateSignInSettings` writes them.
 */
export type SignInSettings = { 
/**
 * Everyone signing in or registering must pass a Cloudflare Turnstile check first. Off
 * unless an admin turns it on.
 */
require_turnstile_sign_in: boolean, };
