// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainNode } from "./DomainNode";

/**
 * Recursive tree structure for representing the full hierarchy
 */
export type TreeNode = { node: DomainNode, children: Array<TreeNode>, };
