// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight workspace metadata for listing multiple workspaces.
 * Excludes large fields like office lists to reduce payload size.
 */
export type WorkspaceMetadata = { id: string, name: string, description: string, owner_id: string, 
/**
 * Whether this is the default (sentinel) workspace
 */
is_default: boolean, member_count: number, };
