// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A change to the workspace icon, carried by `UpdateWorkspaceProfile`.
 *
 * Stored under the workspace metadata's `logo` key: a small raster image as a
 * data URL (WebP, PNG or JPEG; never SVG, which can carry script), or `null`
 * once cleared.
 */
export type WorkspaceLogoChange = { "Set": { data_url: string, } } | "Clear";
