// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupMessageType } from "./GroupMessageType";
import type { Permission } from "./Permission";
import type { UpdateOperation } from "./UpdateOperation";
import type { UserRole } from "./UserRole";

export type WorkspaceProtocolRequest = { "CreateWorkspace": { name: string, description: string, workspace_master_password: string, metadata: Array<number> | null, } } | "GetWorkspace" | { "UpdateWorkspace": { name: string | null, description: string | null, workspace_master_password: string, metadata: Array<number> | null, } } | { "DeleteWorkspace": { workspace_master_password: string, } } | { "CreateOffice": { workspace_id: string, name: string, description: string, mdx_content: string | null, metadata: Array<number> | null, } } | { "GetOffice": { office_id: string, } } | { "UpdateOffice": { office_id: string, name: string | null, description: string | null, mdx_content: string | null, metadata: Array<number> | null, } } | { "DeleteOffice": { office_id: string, } } | "ListOffices" | { "CreateRoom": { office_id: string, name: string, description: string, mdx_content: string | null, metadata: Array<number> | null, } } | { "GetRoom": { room_id: string, } } | { "UpdateRoom": { room_id: string, name: string | null, description: string | null, mdx_content: string | null, metadata: Array<number> | null, } } | { "DeleteRoom": { room_id: string, } } | { "ListRooms": { office_id: string, } } | { "AddMember": { user_id: string, office_id: string | null, room_id: string | null, role: UserRole, metadata: Array<number> | null, } } | { "GetMember": { user_id: string, } } | { "UpdateMemberRole": { user_id: string, role: UserRole, metadata: Array<number> | null, } } | { "UpdateMemberPermissions": { user_id: string, domain_id: string, permissions: Array<Permission>, operation: UpdateOperation, } } | { "RemoveMember": { user_id: string, office_id: string | null, room_id: string | null, } } | { "ListMembers": { office_id: string | null, room_id: string | null, } } | { "Message": { contents: Array<number>, } } | { "SendGroupMessage": { 
/**
 * UUID of the group chat channel (office.chat_channel_id or room.chat_channel_id)
 */
group_id: string, 
/**
 * Type of message (text, markdown, system)
 */
message_type: GroupMessageType, 
/**
 * Message content
 */
content: string, 
/**
 * ID of message being replied to (for threading)
 */
reply_to: string | null, 
/**
 * List of mentioned usernames
 */
mentions: Array<string> | null, } } | { "EditGroupMessage": { group_id: string, message_id: string, new_content: string, } } | { "DeleteGroupMessage": { group_id: string, message_id: string, } } | { "GetGroupMessages": { group_id: string, 
/**
 * Get messages before this timestamp (for pagination)
 */
before_timestamp: bigint | null, 
/**
 * Maximum number of messages to return
 */
limit: number | null, } } | { "GetThreadMessages": { group_id: string, 
/**
 * The parent message ID
 */
parent_message_id: string, } };
