// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupMessage } from "./GroupMessage";
import type { Office } from "./Office";
import type { Room } from "./Room";
import type { User } from "./User";
import type { Workspace } from "./Workspace";

export type WorkspaceProtocolResponse = { "Workspace": Workspace } | { "Success": string } | { "Error": string } | "WorkspaceNotInitialized" | { "Offices": Array<Office> } | { "Rooms": Array<Room> } | { "Members": Array<User> } | { "Office": Office } | { "Room": Room } | { "Member": User } | { "GroupMessageNotification": { group_id: string, message: GroupMessage, } } | { "GroupMessages": { group_id: string, messages: Array<GroupMessage>, has_more: boolean, } } | { "GroupMessageEdited": { group_id: string, message_id: string, new_content: string, edited_at: bigint, } } | { "GroupMessageDeleted": { group_id: string, message_id: string, deleted_by: string, } } | { "GroupMessage": GroupMessage };
