// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceProtocolRequest } from "./WorkspaceProtocolRequest";
import type { WorkspaceProtocolResponse } from "./WorkspaceProtocolResponse";

export type WorkspaceProtocolPayload = { "Request": WorkspaceProtocolRequest } | { "Response": WorkspaceProtocolResponse };
