// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Office } from "./Office";
import type { Room } from "./Room";
import type { User } from "./User";
import type { Workspace } from "./Workspace";

export type WorkspaceProtocolResponse = { "Workspace": Workspace } | { "Success": string } | { "Error": string } | "WorkspaceNotInitialized" | { "Offices": Array<Office> } | { "Rooms": Array<Room> } | { "Members": Array<User> } | { "Office": Office } | { "Room": Room } | { "Member": User };
