/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const close_connection: () => any;
export const ensure_messenger_open: (a: number, b: number) => any;
export const get_version: () => [number, number];
export const init: (a: number, b: number) => any;
export const is_initialized: () => number;
export const main: () => void;
export const next_message: () => any;
export const open_messenger_for: (a: number, b: number) => any;
export const restart: (a: number, b: number) => any;
export const send_direct_to_internal_service: (a: any) => any;
export const send_p2p_message_reliable: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const wasm_bindgen_5f14a889508d6a35___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut__web_sys_9e969595e8421720___features__gen_CloseEvent__CloseEvent____Output_______: (a: number, b: number) => void;
export const wasm_bindgen_5f14a889508d6a35___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut__web_sys_9e969595e8421720___features__gen_MessageEvent__MessageEvent____Output_______: (a: number, b: number) => void;
export const wasm_bindgen_5f14a889508d6a35___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut__wasm_bindgen_5f14a889508d6a35___JsValue____Output_______: (a: number, b: number) => void;
export const wasm_bindgen_5f14a889508d6a35___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut_____Output_______: (a: number, b: number) => void;
export const wasm_bindgen_5f14a889508d6a35___closure__destroy___dyn_core_7d5f0a2ba6a62c33___ops__function__FnMut_____Output________1_: (a: number, b: number) => void;
export const wasm_bindgen_5f14a889508d6a35___convert__closures_____invoke___wasm_bindgen_5f14a889508d6a35___JsValue__wasm_bindgen_5f14a889508d6a35___JsValue_____: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_5f14a889508d6a35___convert__closures_____invoke___web_sys_9e969595e8421720___features__gen_CloseEvent__CloseEvent_____: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5f14a889508d6a35___convert__closures_____invoke___web_sys_9e969595e8421720___features__gen_MessageEvent__MessageEvent_____: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5f14a889508d6a35___convert__closures_____invoke___wasm_bindgen_5f14a889508d6a35___JsValue_____: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5f14a889508d6a35___convert__closures_____invoke______: (a: number, b: number) => void;
export const wasm_bindgen_5f14a889508d6a35___convert__closures_____invoke_______1_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
