/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const close_connection: () => any;
export const ensure_messenger_open: (a: number, b: number) => any;
export const get_version: () => [number, number];
export const init: (a: number, b: number) => any;
export const is_initialized: () => number;
export const main: () => void;
export const next_message: () => any;
export const open_messenger_for: (a: number, b: number) => any;
export const restart: (a: number, b: number) => any;
export const send_direct_to_internal_service: (a: any) => any;
export const send_p2p_message_reliable: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const wasm_bindgen__closure__destroy__h91391c245e9d53ad: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__haac3b7e79ff750e6: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h2cf7294972d30e90: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hf8953c6b3532ea93: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__ha69d84634221b2bd: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1b9ed81134d7c53f: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1d6156b95a554736: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h99790b6128a1ce38: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha8c6e112b0b9df11: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
