/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const close_connection: () => any;
export const ensure_messenger_open: (a: number, b: number) => any;
export const get_version: () => [number, number];
export const init: (a: number, b: number) => any;
export const is_initialized: () => number;
export const main: () => void;
export const next_message: () => any;
export const open_messenger_for: (a: number, b: number) => any;
export const restart: (a: number, b: number) => any;
export const send_direct_to_internal_service: (a: any) => any;
export const send_p2p_message_reliable: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const wasm_bindgen__convert__closures_____invoke__hcb276ed5a66c764a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h968876f9daa86614: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hdf5e65de09412ac5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__ha12fde1bb25c46b1: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h10ef8c18e087d6ee: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hc929a81066918af1: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb9de5abb9c633eef: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__hd46220dca824cea7: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h7af0fdeabf4da7a7: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
