// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigCommand = { "SetConnectionOrphan": { allow_orphan_sessions: boolean, } } | { "ClaimSession": { session_cid: bigint, only_if_orphaned: boolean, } } | { "DisconnectOrphan": { session_cid: bigint | null, } } | { "ReleaseSession": { session_cid: bigint, } };
