// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionManagementSuccess = { cid: bigint, request_id: string | null, message: string, };
